package genai.chatGPT;
/*
Enter here the GenAi Prompt:
 Generate a JML specification and a java code for method public static int bubbleSort(int[] arr) that sorts an integer array in ascending order.
 The method takes an integer array arr[] as input and returns the array sorted from the smallest to the largest value.
 The method returns the sorted array, ensuring that all elements are ordered from the smallest to the largest.
 */
public class BubbleSort {
    /*@
       requires arr != null;

       // The array length remains unchanged
       ensures arr.length == \old(arr.length);

     @*/
    public static void bubble(int[] arr) {
        int n = arr.length;

        for (int i = 0; i < n - 1; i++) {
            for (int j = 0; j < n - i - 1; j++) {
                if (arr[j] > arr[j + 1]) {
                    // Swap arr[j] and arr[j+1]
                    int temp = arr[j];
                    arr[j] = arr[j + 1];
                    arr[j + 1] = temp;
                }
            }
        }
    }
}
/*store here your opinion about the quality of the generated spec
The JMl specification generated by chatGPT follows a different format that may need to be edited depending on whether the program has a difficulty reading and interpreting it, Found that "/forall" is not translated correctly within Taco.

 */

    /*store here your opinion about the quality of the generated code
Concise and short code, following good logic. Code presented no problems during testing.
     */
/*store here the result of the analysis with TACO
Warning #1
== is redundant, because the left and right expressions always have the same value.
Left type = {this/true}
Right type = {this/true}
Warning #2
== is redundant, because the left and right expressions always have the same value.
Left type = {this/true}
Right type = {this/true}

 */

    /*if TACO's outcome was "SAT: A failure has been detected", store here
    the source code of the method in folder "generated" that describes the
    counterexample. Otherwise report "UNSAT".
UNSAT
     */


