package genai.chatGPT;
/*
Enter here the GenAi Prompt:
 Generate a JML specification and a java code for method public static int bubbleSort(int[] arr) that sorts an integer array in ascending order.
 The method takes an integer array arr[] as input and returns the array sorted from the smallest to the largest value.
 The method returns the sorted array, ensuring that all elements are ordered from the smallest to the largest.
 */
public class BubbleSort {
    /*@
       requires arr != null;

       // The array length remains unchanged
       ensures arr.length == \old(arr.length);

       // The array is sorted in ascending order
       ensures (\forall int i; 0 <= i && i < arr.length - 1; arr[i] <= arr[i + 1]);

       // The sorted array is a permutation of the original array
       ensures (\forall int v;
                   (\num_of int i; 0 <= i && i < arr.length; arr[i] == v) ==
                   (\num_of int i; 0 <= i && i < \old(arr.length); \old(arr[i]) == v)
               );
     @*/
    public static void bubble(int[] arr) {
        int n = arr.length;

        for (int i = 0; i < n - 1; i++) {
            for (int j = 0; j < n - i - 1; j++) {
                if (arr[j] > arr[j + 1]) {
                    // Swap arr[j] and arr[j+1]
                    int temp = arr[j];
                    arr[j] = arr[j + 1];
                    arr[j + 1] = temp;
                }
            }
        }
    }
}
/*store here your opinion about the quality of the generated spec
The JMl specification generated by chatGPT follows a different format that may need to be edited depending on whether the program has a difficulty reading and interpreting it.

 */

    /*store here your opinion about the quality of the generated code
Concise and short code, following good logic.
     */
/*store here the result of the analysis with TACO


 */

    /*if TACO's outcome was "SAT: A failure has been detected", store here
    the source code of the method in folder "generated" that describes the
    counterexample. Otherwise report "UNSAT".

     */


