package genai.chatGPT;

public class Calculator {
    //Prompt: Generate a JML specification and a method implementation
    // that takes two numbers and an operator, then does the correct math operation
    // based on the operator. It uses a switch to check if the operator is +, -, *, /,
    // or %, and returns the result. If the operator isnt valid, it returns -1.

//Generated JML Spec:

/*@ requires operator == '+' || operator == '-' || operator == '*' || operator == '/' || operator == '%' || (operator != '+' && operator != '-' && operator != '*' && operator != '/' && operator != '%');
@ ensures (operator == '+') ==> \result == a + b;
@ ensures (operator == '-') ==> \result == a - b;
@ ensures (operator == '*') ==> \result == a * b;
@ ensures (operator == '/' && b != 0) ==> \result == a / b;
@ ensures (operator == '%' && b != 0) ==> \result == a % b;
@ ensures (operator != '+' && operator != '-' && operator != '*' && operator != '/' && operator != '%') ==> \result == -1;
@ ensures (operator == '/' && b == 0) ==> \result == -1;
@ ensures (operator == '%' && b == 0) ==> \result == -1;
@*/
    //Generated code:
    public static int calculate(int a, int b, char operator) {
        switch (operator) {
            case '+':
                return a + b;
            case '-':
                return a - b;
            case '*':
                return a * b;
            case '/':
                if (b == 0) return -1;
                return a / b;
            case '%':
                if (b == 0) return -1;
                return a % b;
            default:
                return -1;
        }
    }

}
/*store here your opinion about the quality of the generated spec
The specification given by chatGPT seems to be too detailed, over-complicated. While
running the test on this file, it appears that many expressions are not in the scope,
or that the parser is 'confused' by unsupported syntax in the JML spec. It is overloaded

 */

    /*store here your opinion about the quality of the generated code
The code generated by chatGPT seems to follow good logic, and while performing an edge case it seems to work correctly.
/*store here the result of the analysis with TACO
13:15:57,716 ERROR JmlParser:59 - org.multijava.util.compiler.CompilationAbortedException
File "output/genai/chatGPT/Calculator.java", line 40, character 34 error: Variable "t_1" is not defined in current context
File "output/genai/chatGPT/Calculator.java", line 42, character 34 error: Variable "t_2" is not defined in current context
File "output/genai/chatGPT/Calculator.java", line 44, character 34 error: Variable "t_3" is not defined in current context
File "output/genai/chatGPT/Calculator.java", line 46, character 21 error: Variable "t_4" is not defined in current context
File "output/genai/chatGPT/Calculator.java", line 59, character 34 error: Variable "t_5" is not defined in current context

 */

    /*if TACO's outcome was "SAT: A failure has been detected", store here
    the source code of the method in folder "generated" that describes the
    counterexample. Otherwise report "UNSAT".

     */