package genai.chatGPT;

public class Calculator {
    //Prompt: Generate a JML specification and a method implementation
    // that takes two numbers and an operator, then does the correct math operation
    // based on the operator. It uses a switch to check if the operator is +, -, *, /,
    // or %, and returns the result. If the operator is not valid, it returns -1.

//Generated JML Spec:

/*@
  @ ensures operator == '+' ==> \result == a + b;
  @ ensures operator == '-' ==> \result == a - b;
  @ ensures operator == '*' ==> \result == a * b;
  @ ensures operator == '/' && b != 0 ==> \result == a / b;
  @ ensures operator == '%' && b != 0 ==> \result == a % b;
  @ ensures (operator == '/' && b == 0) ==> \result == -1;
  @ ensures (operator == '%' && b == 0) ==> \result == -1;
  @ ensures (operator != '+' &&
             operator != '-' &&
             operator != '*' &&
             operator != '/' &&
             operator != '%')
             ==> \result == -1;
@*/

    //Generated code:
    public static int calculate(int a, int b, char operator) {
        switch (operator) {
            case '+': return a + b;
            case '-': return a - b;
            case '*': return a * b;
            case '/': return (b == 0) ? -1 : a / b;
            case '%': return (b == 0) ? -1 : a % b;
            default: return -1;
        }
    }
    }

/*store here your opinion about the quality of the generated spec
The specification given by chatGPT seems to be too detailed, over-complicated. While
running the test on this file, it appears that many expressions are not in the scope,
or that the parser is 'confused' by unsupported syntax in the JML spec. It is overloaded

 */

    /*store here your opinion about the quality of the generated code
The code generated by chatGPT seems to follow good logic, and while performing an edge case it seems to work correctly.
/*store here the result of the analysis with TACO
00001117  Translating Alloy to Kodkod

    * Solver                  : sat4j
    * Bit width               : 2
    * Max sequence            : 0
    * Skolem depth            : 0
    * Symmbreaking            : 20

00001421  Translating Kodkod to CNF

    * Primary vars            : 16829
    * Total vars              : 259724
    * Clauses                 : 587995

00004089  Solving

    * Outcome                 : SAT: A failure has been detected.
    * Solving time            : 28717

00030066  Analysis finished

JUnit generation: started
         ... and finished.

Process finished with exit code 0

 */

    /*if TACO's outcome was "SAT: A failure has been detected", store here
    the source code of the method in folder "generated" that describes the
    counterexample. Otherwise report "UNSAT".
SAT
     */