package genai.chatGPT;
//Prompt for second test:
//Generate a JML specification for the method public static int find_in_sorted(int[] arr, int x), which searches for the integer x in a sorted integer array arr using the binsearch method.
//
//Notes:
//The purpose of this prompt differing from the last one was to make it short and generalized, attempting to avoid complicated annotation.
public class Find_in_Sorted_2 {
    /*@
  @ requires arr != null;
  @ requires (\forall int i; 0 <= i && i < arr.length - 1; arr[i] <= arr[i+1]);
  @
  @ ensures
  @   // If x does not appear, result is -1
  @   (\result == -1 ==>
  @        (\forall int i; 0 <= i && i < arr.length; arr[i] != x));
  @
  @ ensures
  @   // If an index is returned, it must be valid and contain x
  @   (\result != -1 ==>
  @        0 <= \result && \result < arr.length
  @        && arr[\result] == x);
  @
  @ ensures
  @   // If x exists somewhere, result is NOT -1
  @   ((\exists int i; 0 <= i && i < arr.length; arr[i] == x)
  @       ==> \result != -1);
  @
  @ pure;
  @*/
    public static int find_in_sorted(int[] arr, int x) {

        int low = 0;
        int high = arr.length - 1;

    /*@ loop_invariant
      @     0 <= low && low <= arr.length &&
      @     -1 <= high && high < arr.length &&
      @     high + 1 >= low &&
      @
      @     // x cannot be in the part already discarded on the left
      @     (\forall int i; 0 <= i && i < low; arr[i] != x) &&
      @
      @     // x cannot be in the part already discarded on the right
      @     (\forall int i; high < i && i < arr.length; arr[i] != x);
      @
      @ decreases high - low;
      @*/
        while (low <= high) {

            int mid = (low + high) / 2;

            if (arr[mid] == x) {
                return mid;
            } else if (arr[mid] < x) {
                low = mid + 1;
            } else {
                high = mid - 1;
            }
        }

        return -1;
    }
}
// On this test, the code and JML annotation generated by ChatGPT proved faulty, as the JML specification
//triggered confusion with the scopes that the model generated.
