package genai.chatGPT;
//Prompt:
//Generate a JML specification and a code implementation for the method public long select that takes in two integers, n and r, and a boolean flag. If flag is true, the method computes the combination of n and r; otherwise, it computes the permutation of n and r.
public class Select {
    /*@
       @ requires n >= 0 && r >= 0 && r <= n && n <= 12; // Bound to prevent explosion
       @ ensures \result >= 0;
       @
       @ // If flag is true, returns C(n,r)
       @ // If flag is false, returns P(n,r)
       @*/
    public static long select(int n, int r, boolean flag) {
        if (flag) {
            return factorial(n) / (factorial(r) * factorial(n - r));
        } else {
            return factorial(n) / factorial(n - r);
        }
    }

    public static long fact(int num) {
        long result = 1;
        for (int i = 2; i <= num; i++) {
            result *= i;
        }
        return result;
    }


}
/*store here your opinion about the quality of the generated spec
The specifications generated by chatGPT were short and clear, correctly parsed by TACO
 */

    /*store here your opinion about the quality of the generated code
The code implementation followed a good logic, correctly solving the problem prompted.
/*store here the result of the analysis with TACO

13:15:57,716 ERROR JmlParser:59 - org.multijava.util.compiler.CompilationAbortedException
File "output/genai/chatGPT/Calculator.java", line 40, character 34 error: Variable "t_1" is not defined in current context
File "output/genai/chatGPT/Calculator.java", line 42, character 34 error: Variable "t_2" is not defined in current context
File "output/genai/chatGPT/Calculator.java", line 44, character 34 error: Variable "t_3" is not defined in current context
File "output/genai/chatGPT/Calculator.java", line 46, character 21 error: Variable "t_4" is not defined in current context
File "output/genai/chatGPT/Calculator.java", line 59, character 34 error: Variable "t_5" is not defined in current context

 */

    /*if TACO's outcome was "SAT: A failure has been detected", store here
    the source code of the method in folder "generated" that describes the
    counterexample. Otherwise report "UNSAT".
UNSAT
     */
