package gemini;
import java.util.Arrays;

public class BubbleSort {
//    JML specification given by gemini:

    /*@ public normal_behavior
      @ requires arr != null;
      @ ensures \result != null && \result.length == \old(arr.length);
      @ ensures (\forall int i; 0 <= i && i < \result.length - 1; \result[i] <= \result[i+1]);
      @ ensures (\forall int i; 0 <= i && i < \result.length;
      @          (\num_of int j; 0 <= j && j < \old(arr.length); \result[i] == \old(arr[j])) ==
      @          (\num_of int k; 0 <= k && k < \result.length; \result[i] == \result[k]));
      @ assignable \nothing;
      @*/

    //Code provided by gemini (java.util.Arrays generated by gemini)
    public static int[] bubbleSort(int[] arr) {
        if (arr == null) {
            return null;
        }
        int[] sortedArr = Arrays.copyOf(arr, arr.length);
        int n = sortedArr.length;

        for (int i = 0; i < n - 1; i++) {
            boolean swapped = false;
            for (int j = 0; j < n - 1 - i; j++) {
                if (sortedArr[j] > sortedArr[j + 1]) {
                    // Swap elements
                    int temp = sortedArr[j];
                    sortedArr[j] = sortedArr[j + 1];
                    sortedArr[j + 1] = temp;
                    swapped = true;
                }
            }
            if (!swapped) {
                break;
            }
        }
        return sortedArr;
    }
}
/*store here your opinion about the quality of the generated spec
The JMl specification generated by Gemini is extensive and detailed, ensuring several conditions are met in order the code works correctly.

 */

    /*store here your opinion about the quality of the generated code
Contrasting with the chatGPT code implementation this approach is longer, less practical. However, this approach creates a new array to avoid directly modifying the original
array.
     */
/*store here the result of the analysis with TACO


 */

    /*if TACO's outcome was "SAT: A failure has been detected", store here
    the source code of the method in folder "generated" that describes the
    counterexample. Otherwise report "UNSAT".

     */
