package gemini;
//Prompt:
//Generate a JML specification for the Factorial class and its methods, specifically the factorial(int n) method, which computes the factorial of an integer n where 0<=n<=20 and the spec factorial(int n) method, which is a recursive model function used for specifying the factorial logic.
public class Factorial {
    /*@ public pure model
      @ requires n >= 0;
      @ ensures \result >= 0;
      @ also
      @ requires n == 0; // <-- NO modifiers here
      @ ensures \result == 1;
      @ also
      @ requires n > 0;
      @ ensures \result == n * spec_factorial(n - 1);
      @*/
    public static int spec_factorial(int n) {
        // This is a JML model and should not be executed.
        throw new UnsupportedOperationException("This is a JML model method.");
    }

    //-------------------------------------------------------------------------

    public static long factorial(int n) {
        if (n < 0 || n > 20) {
            throw new IllegalArgumentException("Input must be between 0 and 20.");
        }

        long result = 1;
        for (int i = 2; i <= n; i++) {
            result *= i;
        }
        return result;
    }
}

/*store here your opinion about the quality of the generated spec
JML specifications generated by gemini were short and concise, however, they failed at compilation and the genAI had to be re-prompted.
 */

    /*store here your opinion about the quality of the generated code
The code implementation followed a good logic, correctly solving the problem prompted.
/*store here the result of the analysis with TACO

13:15:57,716 ERROR JmlParser:59 - org.multijava.util.compiler.CompilationAbortedException

 */

    /*if TACO's outcome was "SAT: A failure has been detected", store here
    the source code of the method in folder "generated" that describes the
    counterexample. Otherwise report "UNSAT".
UNSAT
     */
