package gemini;
//Prompt for generative AI:  Generate a JML specification and a code implementation for the method public static long permutation that takes
// in two integers, n and r, in order to compute the number of ways to arrange r elements from a set of n elements where order matters.
public class Permutation {

    //JML spec generated:
    /*@requires n >= 0 && r >= 0 && n >= r;
  @*/

    //code implementation:
    public static long permutations(int n, int r) {

        if (r < 0) {
            throw new IllegalArgumentException();
        }
        if( n < r){
            throw new IllegalArgumentException();

        }

        long result = 1;
        for (int i = 0; i < r; i++) {
            result *= (n - i);
        }
        return result;
    }
/*store here your opinion about the quality of the generated spec
The specification given by chatGPT seems to be too detailed, over-complicated. While
running the test on this file, it appears that many expressions are not in the scope,
or that the parser is 'confused' by unsupported syntax in the JML spec. It is overloaded

 */

    /*store here your opinion about the quality of the generated code
The code generated by chatGPT seems to follow good logic, and while performing an edge case it seems to work correctly.
/*store here the result of the analysis with TACO
13:15:57,716 ERROR JmlParser:59 - org.multijava.util.compiler.CompilationAbortedException
File "output/genai/chatGPT/Calculator.java", line 40, character 34 error: Variable "t_1" is not defined in current context
File "output/genai/chatGPT/Calculator.java", line 42, character 34 error: Variable "t_2" is not defined in current context
File "output/genai/chatGPT/Calculator.java", line 44, character 34 error: Variable "t_3" is not defined in current context
File "output/genai/chatGPT/Calculator.java", line 46, character 21 error: Variable "t_4" is not defined in current context
File "output/genai/chatGPT/Calculator.java", line 59, character 34 error: Variable "t_5" is not defined in current context

 */

    /*if TACO's outcome was "SAT: A failure has been detected", store here
    the source code of the method in folder "generated" that describes the
    counterexample. Otherwise report "UNSAT".

     */

}
